### ISSUE TITLE
[Dark Mode] iTunes freezes when apply any of those filter (Eg. dark mode)

### ISSUE THREAD

**Issue by icestraw** [BiGilSoft/WindowTop#218] opened 2022-04-29 16:57 UTC

**Comment by gileli121** [comment] 2022-05-08 20:09
Thanks for the report.
Do you use Windows 11 or Windows 10?

I am not working on fixing a few bugs in the dark-mode feature because I see from users that it is important.
I worked on:
https://github.com/BiGilSoft/WindowTop/issues/220
https://github.com/BiGilSoft/WindowTop/issues/225 

Can you check if you still get the issue with the version that I posed in #220 ?

**Comment by gileli121** [comment] 2022-05-08 22:21
@icestraw 
The latest test version is in #226 

Download:
[WindowTop 5.12.1-beta2 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/8647891/WindowTop.5.12.1-beta2.-.setup.exe.zip) 

Let me know if just in case the problem fixed.

**Comment by icestraw** [comment] 2022-05-12 15:33
I'm using windows 11 and the bug still exists.

**Comment by gileli121** [comment] 2022-05-14 18:43
@icestraw 
I was able to reproduce the problem.
I am checking it now

**Comment by gileli121** [comment] 2022-05-14 19:07
Fix in progress

**Comment by gileli121** [comment] 2022-05-14 20:28
@icestraw 
After investigation, it seems that you can reproduce it when you try to enable opacity.
It seems that iTunes windows get frozen when you enable opacity for it.
Since the dark mode filter also tried to set temporary opacity, it also froze the app.

The solution is to not set the opacity at all in this case. The dark mode filter can work also without it.
But I also removed the button to enable opacity for unsupported apps like iTunes

Please try this version and let me know if it is fixed:
[WindowTop 5.12.1-beta3 - setup.ex.zip](https://github.com/BiGilSoft/WindowTop/files/8693804/WindowTop.5.12.1-beta3.-.setup.exe.zip)

**Comment by gileli121** [comment] 2022-05-14 22:04
@icestraw 
Please test this version instead:
[WindowTop 5.12.1-beta4 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/8693954/WindowTop.5.12.1-beta4.-.setup.exe.zip)


I just changed a little how logging works in the dark-mode filter.
I don't think that it will break it. Anyway, better to be safe.

Thanks

**Comment by icestraw** [comment] 2022-05-15 12:47
It works in this version. : )
There's still a small problem: when in dark mode, the long press event of mouse becomes dragging. When I clicked on a song, the "move to new playlist" sidebar accidenly shows, which doesn't show when not in dark mode. I don't know the cause.

**Comment by gileli121** [comment] 2022-05-15 15:42
@icestraw 
Great!

About the other issue, I need some recordings of the issue.
Is it a big issue or something minor?

**Comment by icestraw** [comment] 2022-05-15 16:13
Minor issue, seems also related to the iTunes itself. Other apps seem fine. Since iTunes on Windows is nearly unmaintained, I think your code may just be okay. I cannot record this effect because I cannot record "mouse long press". It just like I din't do anything at all...

**Comment by gileli121** [comment] 2022-05-15 20:28
@icestraw 
Thanks, can you please check the last version from here:
https://github.com/BiGilSoft/WindowTop/issues/229 

Please comment there and let me know if it works fine.
If it is fine, it will be the final release.

Thank you

**Comment by icestraw** [comment] 2022-05-16 05:39
UI is fine, the frezzing issue gone, the minor issue still exists.
I try to record it properly FYI

https://user-images.githubusercontent.com/7201592/168526363-8ce10ec9-b32c-4e56-be21-88f243325409.mp4

.

**Comment by gileli121** [comment] 2022-05-17 17:47
Released in https://github.com/BiGilSoft/WindowTop/releases/tag/v5.12.1
Please open another issue about it if you want

**Closed by gileli121** 2022-05-17 17:47 UTC
Labels: bug, fixed, testing...
