### ISSUE TITLE
Red Border Frame Always On, Regardless of Setting, After Shrink/Restore or Switch desktops

### ISSUE THREAD

**Issue by dreamcasting** [BiGilSoft/WindowTop#122] opened 2021-07-21 17:35 UTC
Hello!

I'm using WindowTop 5.4.8 Portable on Windows 10 19042.1083. When shrinking a window I've clicked "Set Top" to and then restoring it to full size later, the red border frame always comes back, regardless of setting in WindowTop. Can this be fixed?

Workaround: Enable and disable "Highlight top most windows with red border" to remove frame.

Thank you!

**Comment by gileli121** [comment] 2021-07-22 15:57
@dreamcasting 
Sorry for the late reply.
I will check it once I will finish with task 

https://github.com/BiGilSoft/WindowTop/issues/94

**Comment by gileli121** [comment] 2021-07-28 06:15
@dreamcasting 
Sorry, I can't reproduce the issue.

Can you describe it in steps?
Maybe I got it wrong.

**Comment by dreamcasting** [comment] 2021-07-28 13:41
1. Start WindowTop Portable
2. Start Telegram
3. Hover over top window bar for Telegram to show WindowTop floating menu
4. Click "Shrink"
5. Click the app to switch it back to full size.
6. At this point the window border will appear in red, requiring the workaround.

**Comment by gileli121** [comment] 2021-07-28 17:10
@dreamcasting 
I did exactly the steps, but in step 6 I did not saw any red border around the telegram window.
I did saw another issue, but it has nothing to do with the red border.
If in step 6 you close the telegram window, it will come back... Maybe you are talking about this behavior?

**Comment by dreamcasting** [comment] 2021-07-28 17:44
No, it definitely is this behavior. The frame doesn't even move with the
window. Screen attached.
[image: image.png]

**Comment by gileli121** [comment] 2021-07-29 04:26
@dreamcasting 
Can you send the screenshot via a regular link?
I can't see it and did not get it in my email

**Comment by dreamcasting** [comment] 2021-07-29 04:46
My bad.
https://photos.app.goo.gl/ptDZ5ruGoGPL1LUK9

**Comment by gileli121** [comment] 2021-07-29 04:50
@dreamcasting 

Thanks,
It confirms what you said.
I thought that I already fixed the bug.

Are you sure that you use the last version?

**Comment by dreamcasting** [comment] 2021-07-29 14:00
5.4.8 - App says no updates available.

**Comment by gileli121** [comment] 2021-07-29 18:29
@dreamcasting 
I saw the video.
Nice QA work... 
It crashed after you changed (like a crazy) the settings pages each seconds
It looks like you tried to crash it.

Or you saying that it crashed also in normal use case?
I can try to fix it but from the video it looks like edge case scenario

**Comment by gileli121** [comment] 2021-08-28 10:47
@dreamcasting 
Reproduced thanks to more information that reported here:
https://github.com/BiGilSoft/WindowTop/issues/128#issuecomment-907607779

**Comment by gileli121** [comment] 2021-08-28 11:12
The key part here is to disable the following option 
![image](https://user-images.githubusercontent.com/17680514/131216089-679b3bfe-f606-4851-8f02-b659e57b1f69.png)

Another way to reproduce it is

1. Start Telegram
2. Hover over top window bar for Telegram to show WindowTop floating menu
3. Enable SET-TOP
4. Switch to another desktop
5. Go back to the first desktop
At this point the window border will appear in red, requiring the workaround.

**Comment by gileli121** [comment] 2021-08-28 11:35
The issue was here
![image](https://user-images.githubusercontent.com/17680514/131216424-c7f5155c-0173-4504-b919-103041679899.png)

It should be under ` if (HighlightMode)` condition.
![image](https://user-images.githubusercontent.com/17680514/131216442-a0778ff1-31a0-451b-804f-3e711ed4a1cf.png)

The method `OnCurrentVirtualDesktopPropertyChanged()` is triggered in both scenarios (when changing desktop or when restoring from Shrink mode) and it is fine.

The condition check could be also directly inside `ProcessHighlighter()` method. 
But never mind.. I make sure that in every place the method call is under this condition check.

@dreamcasting and @JaasielCR:

Please try this build and let me know if the problem fixed for you:

[WindowTop Build 28-08-21_1.zip](https://github.com/BiGilSoft/WindowTop/files/7070639/WindowTop.Build.28-08-21_1.zip)


Thanks.

**Comment by dreamcasting** [comment] 2021-08-30 13:52
@gileli121 
That fixed it!

**Comment by gileli121** [comment] 2021-08-30 18:43
Great!
Released in v5.4.15
Closed

**Closed by gileli121** 2021-08-30 18:43 UTC
Labels: bug, high-priority, fixed
