### ISSUE TITLE
Tray icon menu has a total disregard of windows font settings

### ISSUE THREAD

**Issue by mdcclxv** [BiGilSoft/WindowTop#136] opened 2021-09-04 22:17 UTC
Hi there,

You've hard-coded in the tray menu the font face, size and color. Just look at the screenshot and compare. I definitely cannot pay for something like that.
![screenshot](https://user-images.githubusercontent.com/33668915/132109237-9c4e81f5-822b-4746-ab61-73a1bd1af654.png)

You should get the font, color and size from the system and use them. Respect the user's choice.

Best.

**Comment by gileli121** [comment] 2021-09-05 04:12
@mdcclxv 
Thanks for the report.
Do you know what I should change in windows theme to reproduce it?

**Comment by mdcclxv** [comment] 2021-09-06 23:57
You need to install one of CleoDesktop's custom un-signed themes (link bellow). Look for installation instructions, they are not trivial. While this may seem far fetched, there are actually a lot of people performing this kind of install. MS keeps failing us on a true dark theme and the possibility to customize fonts and completely disable font anti-aliasing.

https://cleodesktop.gumroad.com/

I'm using a slightly modified **Photoshop Dark CC** theme, where I replaced the anti-aliased Segoe font with non-antialiased Verdana, but you should be able to reproduce the issue with the original Dark CC theme.

All this aside, if you don't wish to actually install a custom theme, all you have to do is use this when building the tray menu:

https://docs.microsoft.com/en-us/windows/win32/api/uxtheme/nf-uxtheme-getthemesysfont

Or, better yet, use Windows' standard menu, not a skinned one. The standard menu is obeying the theme.

Skinned apps always have trouble keeping up with new stuff, developers should definitely stay away from that.

**Comment by gileli121** [comment] 2021-09-07 09:36
@mdcclxv 
The code uses `System.Windows.SystemColors` from https://docs.microsoft.com/en-us/dotnet/api/system.windows.systemcolors?view=net-5.0 

It using `ControlBrushKey`.

I think that it should use `ActiveCaptionTextColor` 
But to be sure, I built the example from this link:
https://stackoverflow.com/questions/5094447/how-do-i-use-the-correct-windows-system-colors 

Download this file:
[WpfApp1.zip](https://github.com/BiGilSoft/WindowTop/files/7120496/WpfApp1.zip)

Run it and send me screenshot please.

Thanks

**Comment by gileli121** [comment] 2021-09-07 09:39
@mdcclxv 
If you can, I prefer that you do what I asked for 4 themes that 2 of them are dark, and the other 2 are light 

For each screenshot, write the theme name.

Thanks

**Comment by gileli121** [comment] 2021-09-07 10:03
After more checking, I noticed that this tool tells me that these colors are laways the same, no matter if the theme is light or dark.
So I will need to work around it in another way

**Comment by mdcclxv** [comment] 2021-09-07 10:14
@gileli121 Unfortunately I only have one dark theme installed, the one I modified from CleoDesktop. I've attached 3 screenshots, one on dark theme and two on light themes that come preinstalled with Windows.

But you only mentioned the colors. That is half of the problem. The other half is font face, size and antialiasing. I've attached a zoomed screenshot with the differences between your SysColors app and my system with the dark theme. Left side: Verdana, 9pt, non-antialiased. This non-antialiased thing is not just a trifle. I have very good eye-sight and antialiased fonts are giving me headaches, they are waaaay too blurred and unclear, it's like looking through a steamy window. And if you run a search for this issue you'll find there are a lot of people like me that MS doesn't give a s**t about.

Would be nice to address those as well, IMHO they equally important from a user's experience point of view.


Dark theme
![sys colors dark cc modified](https://user-images.githubusercontent.com/33668915/132326331-83966729-b984-4987-b660-e47c3ccf01e4.png)

Standard **Windows** theme
![sys colors windows standard](https://user-images.githubusercontent.com/33668915/132326471-15688b69-74cf-4049-9a5b-feb38da2de6a.png)

Standard **Windows light** theme
![sys colors windows light](https://user-images.githubusercontent.com/33668915/132326577-bf5dbeeb-bf9b-4f83-91d6-935c1fe3c4bf.png)

Zoomed details
![details](https://user-images.githubusercontent.com/33668915/132326624-07fb1e5e-a1c5-431f-a8a1-7fdfb582d646.png)

**Comment by gileli121** [comment] 2021-09-07 10:18
@mdcclxv 
I am going to switch the skin/theme to be based also on 
https://github.com/Kinnara/ModernWpf

It should fix any theme issue

**Comment by gileli121** [comment] 2021-09-07 10:19
@mdcclxv 
You don't have issues in the settings page right?
I am asking because the settings page using the ModernWpf library I posted here

**Comment by mdcclxv** [comment] 2021-09-07 11:13
I guess SysColors are the old way, XP's customization and is very likely that Windows 10 theme engine is totally ignoring them as the colors should be specified by the theme, not by the system.

No issues in the settings window.

**Comment by gileli121** [comment] 2021-09-07 14:34
Maybe.
I am going to use this for the tray menu.
![image](https://user-images.githubusercontent.com/17680514/132363061-a93cebf6-1bcc-4394-b06e-2fe69e9f6461.png)

It looks better?

**Comment by mdcclxv** [comment] 2021-09-07 15:10
Definitely :)

**Comment by gileli121** [comment] 2021-09-07 16:40
@mdcclxv 

See the new screenshots:

Light:
![image](https://user-images.githubusercontent.com/17680514/132380120-1a5f64f1-187d-4e93-bd6e-5943480f55af.png)
![image](https://user-images.githubusercontent.com/17680514/132380197-4402051f-e55d-4b5a-aaaa-6a6de5ff7c8a.png)

Dark:
![image](https://user-images.githubusercontent.com/17680514/132380348-8fe20575-e56f-4d7c-830f-290bf487872a.png)
![image](https://user-images.githubusercontent.com/17680514/132380399-600d41b3-ce0b-4493-bc54-5215c4c06ac6.png)

Try this build:
[WindowTop Build 07-09-21_3.zip](https://github.com/BiGilSoft/WindowTop/files/7123091/WindowTop.Build.07-09-21_3.zip)

Let me know how it works for you.

**Comment by mdcclxv** [comment] 2021-09-07 17:54
Works perfectly.

I just read a bit about WPF framework and it seems that it's impossible to disable font anti-aliasing. Another case of MS shoving stuff down our throats. Since more and more developers are switching to WPF I guess I'll be switching to Linux.

Anyway, I'm glad you sorted this out, I'll be trying the software for a couple of days, see how I cope with transparent windows.

**Comment by gileli121** [comment] 2021-09-07 19:06
Great,
I don't know why to disable AA at all.
For me it looks better with AA.

Anyway, I will mark this issue as fixed/done
Thanks

**Comment by gileli121** [comment] 2021-09-10 12:46
Released in v5.5

**Closed by gileli121** 2021-09-10 12:46 UTC
Labels: bug, fixed, planed-for-v5.(X+1).Y
