### ISSUE TITLE
Transparency settings reset upon restart

### ISSUE THREAD

**Issue by Popedigoz** [BiGilSoft/WindowTop#259] opened 2022-09-19 09:16 UTC
Hello,

So I just downloaded this WindowTop program spesificially for its transparency features. However, I do not want to set the transparency to each and every window/program every time I boot my PC. That would be very tedious and annoying. Why it can't just remember the settings, at least the value is saved but still. And yes I pressed the 'Save Window Configuration'.

 Windows 11.

**Comment by gileli121** [comment] 2022-09-19 10:22
@Popedigoz 
Just need to verify -
Did you click on this button
![image](https://user-images.githubusercontent.com/17680514/190997447-b4941237-14e0-45dd-b7ee-9dc3377ff6cc.png)

Why the Opacity mode enabled?

**Comment by Popedigoz** [comment] 2022-09-19 10:35
> @Popedigoz Just need to verify - Did you click on this button ![image](https://user-images.githubusercontent.com/17680514/190997447-b4941237-14e0-45dd-b7ee-9dc3377ff6cc.png)
> 
> Why the Opacity mode enabled?

yes

**Comment by gileli121** [comment] 2022-09-19 12:19
@Popedigoz 
And you are saying that after you did it and opened another window of the same app - the opacity did not enabled automatically?

This is very strange because it works fine for me also in another computer

**Comment by gileli121** [comment] 2022-09-19 17:27
@Popedigoz 
I see it is the scenario when the window is elevated window (its process runs as Admin user), and in such a case, the app will show you this notification that asks you to click on it so WindowTop will request elevated permission to modify the window state.

On my end, it did work as expected - once I clicked on the notification, the OS asked me if I allowed giving this permission, and after I allowed it, WindowTop loaded the configuration (in this case - enable opacity).

Do you use the portable version?

**Comment by Popedigoz** [comment] 2022-09-19 17:43
>once I clicked on the notification, the OS asked me if I allowed giving this permission, and after I allowed it, WindowTop loaded the configuration (in this case - enable opacity).
 When I clicked it, as I said nothing happened (OS didn't ask me anything)
> Do you use the portable version?
Nope.

**Comment by Popedigoz** [comment] 2022-09-19 17:43
> > once I clicked on the notification, the OS asked me if I allowed giving this permission, and after I allowed it, WindowTop loaded the configuration (in this case - enable opacity).
> > When I clicked it, as I said nothing happened (OS didn't ask me anything)
> 
> 
> > Do you use the portable version?
> > Nope.

**Comment by gileli121** [comment] 2022-09-20 19:48
@Popedigoz 
Please do the following steps:
1. Download this portable version:
[WindowTop.v5.17.0.Portable - With logs enabled.zip](https://github.com/BiGilSoft/WindowTop/files/9610842/WindowTop.v5.17.0.Portable.-.With.logs.enabled.zip)
2. Extract the zip
3. Run WindowTop.exe 
4. Reproduce the problem

After that, exit the app and send me the `WindowTopLog.log` that was created.
Thank you

**Comment by Popedigoz** [comment] 2022-09-21 04:06
> 

@gileli121 
[WindowTopLog.log](https://github.com/BiGilSoft/WindowTop/files/9612856/WindowTopLog.log)

With this version, the program crashes when I press "Start with Windows" from General tab, so this time, I don't even get the popup about WindowTop not being able to automatically apply the saved window configutation.

**Comment by gileli121** [comment] 2022-09-21 04:49
@Popedigoz 
Thank you, I could reproduce the second bug when enabling "Start with Windows" in the portable version.
I am fixing it now.

Anyway - the program crashed when it tried to notify you that enabling this option to start with windows is not supported in the portable version. 

I will send you soon another version with logs enabled and you will need to install this version because "Start with Windows" is not supported in portable mode

**Comment by gileli121** [comment] 2022-09-21 05:28
@Popedigoz
I fixed the second issue.
About the first issue (about this ticket) -I need that you will do these steps:

1. Download and install this version:
[WindowTop 5.17.1-beta1 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/9613247/WindowTop.5.17.1-beta1.-.setup.exe.zip)


2. Download this file:
[NLog.zip](https://github.com/BiGilSoft/WindowTop/files/8247871/NLog.zip)
3. Extract from there the file `NLog.config`
4. Put the `NLog.config` in `C:\Program Files\WindowTop`
5. Start WindowTop 
6. Reproduce the problem, and right after you get the error, exit the app
7. Go to `%appdata%/windowtop`
8. Send me the file `WindowTopLog.log` that was created there.


Thanks.

**Comment by Popedigoz** [comment] 2022-09-21 07:13
> 

@gileli121 
[WindowTopLog.log](https://github.com/BiGilSoft/WindowTop/files/9613940/WindowTopLog.log)

Ok - however, this time, with this version, there was no popup about WindowTop not being able to automatically apply the saved window configutation. The problem still persists.

**Comment by Popedigoz** [comment] 2022-09-21 07:21
My prior troubleshooting testings were done only with Discord, not file explorer - so now as I tried to include file explorer too, seems like the program is working as intended for file explorer, but not with Discord.

**Comment by gileli121** [comment] 2022-09-21 19:34
@Popedigoz 
Try to exit the app, rerun it, and reproduce the problem.
Make sure that you saved the configuration for the window (just in case the uninstall deleted the settings).

The reason I ask you to rerun the app is that the app needs to run without admin privileges, and the installer did run it with admin privileges. 

Then, you will get this notification again when a window with saved configuration is opened.
When it happens, click on the notification as you did before and send me the logs.

Thank you.

**Comment by Popedigoz** [comment] 2022-09-22 06:27
Weird... I can't seem to get the notification (WindowTop not being able to automatically apply the saved window configutation) -popup anymore at all, not with the beta nor with the latest v5.17.0. 

>Make sure that you saved the configuration for the window (just in case the uninstall deleted the settings).
I did.

>The reason I ask you to rerun the app is that the app needs to run without admin privileges, and the installer did run it with admin privileges.

This I did too, I mean to even reproduce it in the first place, I had to reboot my PC, it wouldn't come by exiting and re-launching the program. Doing that wouldn't also give the notification, the app would just work as intended. Only it wouldn't with PC restart/boot

**Comment by gileli121** [comment] 2022-09-22 06:56
@Popedigoz 
If you enabled the second option:
![image](https://user-images.githubusercontent.com/17680514/191677874-bd2ce839-7a3b-4d6f-9da7-0d4cd9ff244e.png)

This will probably solve your issue but not the bug itself.
This is because the app will start as an admin user when the computer boots up.

Does this option is enabled?
Anyway, this is the workaround for the issue.

But please don't enable this option yet because I want to get logs that I can check to troubleshoot the bug.
Let's handle your case this way: just continue to use the app as usual. Please send me the logs when you get such an issue again.
Make sure that the file `NLog.config` file is still there (in case you reinstalled the app or something)

Thank you

**Comment by gileli121** [comment] 2022-09-23 09:45
@Popedigoz 
Please try this version:
https://github.com/BiGilSoft/WindowTop/releases/tag/v5.17.1

Your bug may be fixed in this version

**Comment by Popedigoz** [comment] 2022-09-23 10:41
> @Popedigoz Please try this version: https://github.com/BiGilSoft/WindowTop/releases/tag/v5.17.1
> 
> Your bug may be fixed in this version

@gileli121 
Tried that, it didn't fix it for me.

**Comment by gileli121** [comment] 2022-09-23 13:22
@Popedigoz 
I was able to reproduce the issue with the Discord app, and I could reproduce it only if I restarted the computer.
I can't reproduce it with file explorer.

I will investigate it now.

About the notification that after you click on it - nothing happens. This is another case that I can't reproduce yet.
We seem to talk here about two different bugs, right? The first bug is with the notification, and the second is about opacity not applied to "Discord" after restart (while configuration is saved)

**Comment by gileli121** [comment] 2022-09-23 14:06
@Popedigoz 
Please try this version:
[WindowTop 5.17.2-beta1 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/9634288/WindowTop.5.17.2-beta1.-.setup.exe.zip)

I fixed the bug that the configuration not loaded after the computer boot.
The scenario can be isolated to:
1. Open "Discord" *before* WindowTop
2. Open WindowTop (while configurations are saved for "Discord")

In this case, WindowTop did not apply the saved configurations.
This scenario happens when the computer boots in case the Discord starts before WindowTop.

**Comment by gileli121** [comment] 2022-09-24 17:34
@Popedigoz 
Please try the version from here:
https://github.com/BiGilSoft/WindowTop/issues/260#issuecomment-1257024611

It includes the fixes of both issues (this issue and issue #260)
Thank you.

**Comment by Popedigoz** [comment] 2022-09-25 11:51
>I was able to reproduce the issue with the Discord app, and I could reproduce it only if I restarted the computer.
I can't reproduce it with file explorer.


Sounds right.


>Please try this version:
[WindowTop 5.17.2-beta1 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/9634288/WindowTop.5.17.2-beta1.-.setup.exe.zip)


Skipped this version since you provided even a newer version.


>Please try the version from here:
https://github.com/BiGilSoft/WindowTop/issues/260#issuecomment-1257024611
It includes the fixes of both issues (this issue and issue https://github.com/BiGilSoft/WindowTop/issues/260)
Thank you.


**Now, this version has fixed the issue. Thank you.**

>About the notification that after you click on it - nothing happens. This is another case that I can't reproduce yet.
We seem to talk here about two different bugs, right? The first bug is with the notification, and the second is about opacity not applied to "Discord" after restart (while configuration is saved)

Does the bug with the notification matter anymore, if the main issue is fixed? I mean, can it even occur as this (opacity thing) seems to be working now.


>I fixed the bug that the configuration not loaded after the computer boot.
The scenario can be isolated to:
    Open "Discord" before WindowTop
    Open WindowTop (while configurations are saved for "Discord")


If I had to guess I'd say it's Discord opening before WindowTop, as that wasindeed something happening in my case.

**Comment by gileli121** [comment] 2022-09-25 14:00
@Popedigoz 
Thank you.

> Does the bug with the notification matter anymore, if the main issue is fixed? I mean, can it even occur as this (opacity thing) seems to be working now.

No. I think that the other bug should be solved by the same fix anyway.


I will close this issue after I release a new version.

**Comment by gileli121** [comment] 2022-09-25 19:15
Released in
https://github.com/BiGilSoft/WindowTop/releases/tag/v5.17.2

**Closed by gileli121** 2022-09-25 19:15 UTC
Labels: bug, fixed
