### ISSUE TITLE
Implement an option to hide text for anchors if icons are selected.

### ISSUE THREAD

**Issue by gileli121** [BiGilSoft/WindowTop#181] opened 2021-12-30 18:24 UTC

**Comment by gileli121** [comment] 2021-12-30 21:52
Preview:
![anchor_hide_text_demo](https://user-images.githubusercontent.com/17680514/147790290-83d273f7-ad8c-4962-a4e5-f632458a483f.gif)

**Comment by jakkaas** [comment] 2021-12-31 05:16
It's looking perfect.

**Comment by gileli121** [comment] 2022-01-03 07:41
[WindowTop 5.7.7-beta1 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/7800793/WindowTop.5.7.7-beta1.-.setup.exe.zip)

**Comment by jakkaas** [comment] 2022-01-03 09:22
It's working. But the position of the icons are changing. It should be fixed when I have selected right side fix position.
    On Monday, 3 January, 2022, 01:11:32 pm IST, Gil Eliyahu ***@***.***> wrote:  
 
 


WindowTop 5.7.7-beta1 - setup.exe.zip

**Comment by cpasoft** [comment] 2022-01-03 10:38
With this beta, the icons are not moving away from the text, are they?

**Comment by gileli121** [comment] 2022-01-03 10:49
@cpasoft 
It broke in this version.
I was not supposed to upload it.
To much stuff broke there.

It will take more 1-3 days to finish this feature

**Comment by gileli121** [comment] 2022-01-03 10:52
@jakkaas 
I did not understand you but anyway something indeed got broken with the auto arranging algorithm so now they are not automatically moving anymore.
As I said, I did mistake in this version.. I broke it

**Comment by cpasoft** [comment] 2022-01-03 10:52
It's not problem to me... This is why it is called "beta version"...
Good work, I like this new feature... and please, not stop to uploading beta versions... we will help you reporting bugs and testing things...
Regards!

**Comment by gileli121** [comment] 2022-01-03 10:54
Thanks.
I will continue to upload beta versions but I will try to avoid too much broken versions like the last one :)

**Comment by gileli121** [comment] 2022-01-03 23:12
@cpasoft / @jakkaas 
After more hours of work, I got this result:
![image](https://user-images.githubusercontent.com/17680514/147989745-55a313cc-190c-43b6-95f9-0c61d52d8490.png)
![anchor_icon_only_demo1](https://user-images.githubusercontent.com/17680514/147989756-27071797-a467-4cdf-8c23-7fd8005c126b.gif)

I added these options:
![image](https://user-images.githubusercontent.com/17680514/147989861-444fcfa0-bd76-49c9-86cc-0ba2d91747fe.png)

If you select "By Size", it will make the anchors of the most recent used windows to be bigger relative to other anchors.
This is the method I use when we see only icons..
You can customize the max scale size (default is 2x) and for how many anchors you want to do it. The default is 3.

Given these configuration, if we have this windows:

Window 1 - Used just now
Window 2 - Used before window 1
Window 3 - Used before window 2
Window 4 - Used before window 3

Then you should see that:
* Anchor of window 1 will be bigger by multiple of 2
* Anchor of window 2 will be bigger by multiple of 1.3
* Anchor of window 3 will be bigger by multiple of 0.6
* Anchor of window 4 will be in regular size. it will not scale it because you chose 3 in the settings.

It is a little complex stuff but hope that you got the idea :) 

See the gif.

I uploaded here new beta version:
[WindowTop 5.7.7-beta2 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/7804453/WindowTop.5.7.7-beta2.-.setup.exe.zip)

**Comment by cpasoft** [comment] 2022-01-03 23:15
Great!....

**Comment by cpasoft** [comment] 2022-01-03 23:37
First test... The emphasys scale it's working great. I've setted as 1.68x. 
Now, the icons are moving away from the text again... Everything seems to work fine by now... I'll be testing this days, and I'll report you any problem I could find
Great job my friend!

**Comment by gileli121** [comment] 2022-01-04 00:05
Great!
I also planning to improve a little the auto position algorithm so that when it moving the icons/anchors, it will try to move them in groups. I mean that it will try to avoid from moving them all over the screen. They will be more close to each other when it is possible.

I also optimized the algorithm in the last beta - auto position should work faster or should take less CPU resources because I removed unnecessary recursions. before the optimization, It basically calculated the same auto-positions multiple times. Now it will not do it and work more efficient

**Comment by cpasoft** [comment] 2022-01-04 10:11
I think the position algorithm is good enough, at least for me...
Moving anchors in groups would not be nor easy nor efficient in my opinion. I think it is better to move it separately as now.
The new scaling system and the Dynamic opacity together are working awesome...

![imagen](https://user-images.githubusercontent.com/29692062/148043325-0309dffd-ec53-4e3a-bdfe-82f0d5429e89.png)

**Comment by gileli121** [comment] 2022-01-04 11:03
@cpasoft 
I edited the previous message and I wrote that I decided to not change the auto-position algorithm because I also think that it works good

> The new scaling system and the Dynamic opacity together are working awesome...

Great to hear!

But I think that maybe there are problems when the DPI scaling is above 100% and I did not handle it yet.
In your screen resolution settings, you have more than 100% scaling/DPI?

I will test it also and see how it works with multiple monitors and more than 100% scaling

**Comment by cpasoft** [comment] 2022-01-04 11:29
On the contrary, I have it below 100%. At this moment, I have it at 83% in a 1920x1080 screen.
Now I've setted to 140% and seems to work right... here an snapshot...
![imagen](https://user-images.githubusercontent.com/29692062/148052019-5a8ceff9-94b8-4675-95ec-e9dc1c001ba7.png)

My settings are:
5 anchors in total, Visibility configuration, 3 anchors, icon extra scale 1.92x, show only icon, dynamic opacity on and minimum opacity 21%.
Size:
![imagen](https://user-images.githubusercontent.com/29692062/148052265-53410209-3efe-4059-885c-63b761afd62f.png)

The same configuration in my other screen (1440x900) shows as:
![imagen](https://user-images.githubusercontent.com/29692062/148052488-0132fe79-27fa-405a-8d89-ee9394add40c.png)

If you want that I try something specific, just let me know...

**Comment by cpasoft** [comment] 2022-01-04 11:32
Maybe a relative size depending of the real screen resolution would be great, but I don't know how  difficult it might be.

**Comment by gileli121** [comment] 2022-01-04 11:37
As you already saw, "difficult" is nothing for me.
Implementing this feature requires a lot of knowledge that I have so you don't have to use this word here

I thought to implement something else:
If you have 2 icons or more that are the same icons, it will show the text also when the mouse not above them, and for the other cases it will show only the icon.

what do you think?
I will call it: "Show window title for duplicate icons"
And you can enable/disable this behavior.

**Comment by cpasoft** [comment] 2022-01-04 11:43
Interesting... so if you have, for example, two editors on background, only appears one icon and the name of the edited files next to this single icon... right?
In this example, both editors count as 1 anchor?... I mean, if you have 6 backgrounds windows, you will have 5 icons or just 4, but one of them with text??

**Comment by gileli121** [comment] 2022-01-04 11:49
No, both editors will get each one another anchor.
But because 2 anchors show the same icon (because they use the editor icon), the idea is to show only for these 2 anchors also the text and not only the icon.

Because this way you can tell more easily which belongs to which window.
If all icons are different, it is easy to know by the icons..
But if you have multiple icons that are the same, you can't tell it unless the mouse above the icon (and then you see the text).
So I suggest that in these cases of duplicate icons - show always the text in addition to the icon

**Comment by cpasoft** [comment] 2022-01-04 11:50
I'll try to explain it better... 
> Maybe a relative size depending of the real screen resolution would be great, but I don't know how difficult it might be.

It's usual to have two or more screen in the same computer, and every one might have different resolution. As it stands now, you will have small icons in one screen, but big in the other... It would be great to have the "same visual size" (more or less) in all screens...

**Comment by cpasoft** [comment] 2022-01-04 11:51
> 

Understood!... I like it!

**Comment by cpasoft** [comment] 2022-01-04 11:51
> No, both editors will get each one another anchor.

Understood!... I like it!

**Comment by gileli121** [comment] 2022-01-04 11:51
> I'll try to explain it better...
> 
> > Maybe a relative size depending of the real screen resolution would be great, but I don't know how difficult it might be.
> 
> It's usual to have two or more screen in the same computer, and every one might have different resolution. As it stands now, you will have small icons in one screen, but big in the other... It would be great to have the "same visual size" (more or less) in all screens...

This is why DPI settings invented.
You just need to configure it in WIndows settings.
You can set different DPI for different monitor

**Comment by cpasoft** [comment] 2022-01-04 12:02
> This is why DPI settings invented.
Yes, I know, but i don't want to lose space on my bigger resolution screen. I don't want to make the text and the rest of the environment bigger to see the WindowTop icons in the same size in all screens.

Maybe my poor English it is not enough to explain what I have to say... Sorry about that...

**Comment by gileli121** [comment] 2022-01-04 12:18
@cpasoft 
I see. But maintaining scaling settings per each DPI is a little difficult.. (haha.. I told that you should not use the word and now I use it myself). 

I can make option to ignore the DPI scaling so that if the option enabled, the icons will not scale up with the DPI.
What do you think?

**Comment by cpasoft** [comment] 2022-01-04 12:43
It could be a solution. Anyway, it is not a big problem...
Thanks Gileli... ;-)

**Comment by gileli121** [comment] 2022-01-04 18:49
You are welcome :)
There ware minor DPI issues that I just fixed.
Now I will continue to implement the behavior I talked about (show text for duplicate icons)

**Comment by gileli121** [comment] 2022-01-05 07:04
@cpasoft 
I added now this option:
![image](https://user-images.githubusercontent.com/17680514/148170949-73985f22-fa2f-4106-b905-89a460ab8c4e.png)

This is what it does:
![image](https://user-images.githubusercontent.com/17680514/148174342-e4d12b44-bc83-471c-bbc6-b4b3d2387141.png)

Please check this beta version:
[WindowTop 5.7.7-beta3 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/7812657/WindowTop.5.7.7-beta3.-.setup.exe.zip)

Let me know how it works.
I could broke a lot of stuff again so it will help if you test it.

Thanks :)

**Comment by cpasoft** [comment] 2022-01-05 10:34
Great... Downloading right now...

**Comment by cpasoft** [comment] 2022-01-05 10:51
First test, by now it seems to work everything ok...
The anchors keep away from text. If you have 2 or more open documents with the same app it shows the text next to the icon. The scale and the opacity seems to works right... 

I have a suggestions about this topic:
-> Allow user to select the default icon instead of the big dot  there is now (when there is no icon for the app, for example, setup's windows or something like that).

Another question... How do you choose the black theme for the WindowTop. I have it on gray, and the context menu it is awful...
![imagen](https://user-images.githubusercontent.com/29692062/148205731-b3703369-8c2a-4308-8c75-2fda98cfb476.png)

And again, Thank you! good work.  :-)

**Comment by cpasoft** [comment] 2022-01-05 10:58
Problem detected:

**Comment by cpasoft** [comment] 2022-01-05 11:03
Problem detected:
The keep away from text is not working on the Desktop Telegram Application.
I have tested on the stable version as well, and it seems to not work either, so it is not a problem with the new features.
I don't know why it is not working with this specific application... Maybe should I open a new topic for this??

**Comment by cpasoft** [comment] 2022-01-05 11:16
Another thing... I don't know if this behaviour is right.
If you have two documents open with the same app, but only one is on background, the text is showing.
Also, if you have two documents, and one is minimized, the other one is also showing the text.

Snapshot to explain it:
![imagen](https://user-images.githubusercontent.com/29692062/148208635-a1efbd0a-b3f8-44ce-a38b-48820cbd14c6.png)
I had only one document open in background, but the text is showing...

**Comment by gileli121** [comment] 2022-01-05 17:04
@cpasoft 
This is a bug.
It should show the text only if there is more than 1 icon that is the same.

Do you know how to reproduce it?

About the issues with notepad and notepad++, I know that it is not perfect. It will miss some stuff sometimes.
But for the most part, it correctly detects texts/images to stay away from.

I can suggest you configure a hotkey for toggling the anchors ON/OFF here:
![image](https://user-images.githubusercontent.com/17680514/148258134-e2bb15b4-3a36-4229-b39c-af09f4249f70.png)

This hotkey will enable/disable it so you can quickly disable it when it does not work right

**Comment by cpasoft** [comment] 2022-01-05 20:02
> @cpasoft This is a bug. It should show the text only if there is more than 1 icon that is the same.
> 
> Do you know how to reproduce it?

It's incredible, I cannot reproduce it again...
But it happened to me this morning...
I'm still testing it... If I can find a way to reproduce it, I'll let you know

**Comment by gileli121** [comment] 2022-01-06 07:05
@cpasoft 
I also reproduced it only once and I don't know how it happened.
I think that it works good enough for release. I am right?
About the issue with notepad and notepad++, maybe these is still way to fix it.
But it is extra logic to add to the algorithm.

It is probably because the algorithm sometimes fails to get information about where the texts/images showing on the screen and as a result, it fails to move the icons away from the texts/images.

**Comment by gileli121** [comment] 2022-01-06 08:05
@cpasoft 
I found way for the algorithm to work better with notepad++ and notepad.
I will modify the algorithm and implement it today or tomorrow

**Comment by gileli121** [comment] 2022-01-06 15:11
@cpasoft 
I was able to reproduce the bug now.
I found how to reproduce it

**Comment by gileli121** [comment] 2022-01-06 16:27
New beta version with fixes for:

- Bug that sometimes it shows the text anyway even if there is one icon (not duplicate)
- Bug that sometimes the anchors are located above the other
[WindowTop 5.7.7-beta4 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/7823316/WindowTop.5.7.7-beta4.-.setup.exe.zip)

**Comment by cpasoft** [comment] 2022-01-06 19:13
Great!, Many improvements today... 
I'm downloading the new beta 5 and testing... 
I'll Let you know what I see...

Thanks Gileli... :-)

**Comment by gileli121** [comment] 2022-01-06 20:25
You probably noticed that the opacity of the anchors changed after some delay.
I fixed the issue in beta 6:
[WindowTop 5.7.7-beta6 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/7824522/WindowTop.5.7.7-beta6.-.setup.exe.zip)

**Comment by gileli121** [comment] 2022-01-07 02:02
Fixed in beta 7 issue that in case of UWP apps, it showed the icon when there are 2 windows from 2 different UWP apps.
It detected different UWP apps as windows from one app so it started to show the text when you have more than one UWP window anchor visible.

Before:
![image](https://user-images.githubusercontent.com/17680514/148478851-5362e4c0-f773-45f1-b924-ac128c2a0fb3.png)

Now:
![image](https://user-images.githubusercontent.com/17680514/148479210-cba80895-563d-4b12-becf-05ec92775eb7.png)

Download:
[WindowTop 5.7.7-beta7 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/7825798/WindowTop.5.7.7-beta7.-.setup.exe.zip)

**Comment by gileli121** [comment] 2022-01-07 08:17
First gif:
![anchors_demo](https://user-images.githubusercontent.com/17680514/148513474-4ddbeee7-3a34-4c6d-96cb-e2aae0934688.gif)

**Comment by gileli121** [comment] 2022-01-07 21:56
In beta 8 I improved the user interface of the anchors configuration and added real time preview:
![anchor_settings_demo  ](https://user-images.githubusercontent.com/17680514/148612345-13182b75-2b4a-49de-ba0f-44354ebaf2dd.gif)

Download:
[WindowTop 5.7.7-beta8 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/7831541/WindowTop.5.7.7-beta8.-.setup.exe.zip)

**Comment by cpasoft** [comment] 2022-01-07 22:00
> In beta 8 I improved the user interface of the anchors configuration and added real time preview

Great improvement!... Thanks...
Downloading...

**Comment by gileli121** [comment] 2022-01-07 23:06
Thank you!
I am waiting to see how it works for you.

I think that we are getting close to next release (not beta) :)

**Comment by cpasoft** [comment] 2022-01-07 23:15
Working very well. Just a minor detail, in preview window always shows 5 icons, no matter how many have you selected on the maximum anchors amount selector.

**Comment by gileli121** [comment] 2022-01-08 12:58
This is minor and a little hard to add also this to the preview.
It is not worth the effort.
I think that it is good enough

**Comment by gileli121** [comment] 2022-01-08 13:49
Just found regression with the option "Always show window title for duplicate icons".
I almost released it as a stable version...
There is an issue now that this behavior not working fine anymore

**Comment by gileli121** [comment] 2022-01-08 14:25
@cpasoft  @jakkaas 
Released as v5.7.8
Download from here:
https://github.com/BiGilSoft/WindowTop/releases/tag/v5.7

Enjoy!

**Closed** 2022-01-08 21:20 UTC
Labels: enhancement, done

**Comment by gileli121** [comment] 2022-01-09 10:13
@cpasoft 
Do you think that the new default settings are fine?

**Comment by gileli121** [comment] 2022-01-14 20:51
@cpasoft 
Please write comment in
https://github.com/BiGilSoft/WindowTop/issues/194
If you want that I will give it priority
