### ISSUE TITLE
Flash on opening Windows cmd or Windows explorer

### ISSUE THREAD

**Issue by Pachat** [BiGilSoft/WindowTop#206] opened 2022-02-25 10:22 UTC
Still getting a flash on opening Windows cmd and Windows explorer.

WindowTop 5.10.0
Edition	Windows 10 Family
Version	21H1
Build       19043.1526
Windows Feature Experience Pack 120.2212.4170.0

**Comment by gileli121** [comment] 2022-02-25 12:35
@Pachat 
I don't understand what is the problem and don't remember it.
Did you reported about this problem before?
Can you share screen recording that shows the issue?

Thanks.

**Comment by Pachat** [comment] 2022-02-25 17:57
I did not report before cause it's my first try of your product.

Here is a gif showing the flash at opening the `cmd`. As a developer, I have many of them opening and would so much like to have them opening without flashing.
![dos blank flash](https://user-images.githubusercontent.com/13746133/155763625-09c80c4c-4b97-46b2-8b4e-ab4a3cc9959f.gif)

If you can fix this, I'll certainly buy your product.

**Comment by gileli121** [comment] 2022-02-25 18:47
@Gitoffthelawn 
This never reported before.
It is very unlikely that it caused by WindowTop.
Can you make double check and try it after you exit WindowTop?
Let me know if you still get the issue.

**Comment by Gitoffthelawn** [comment] 2022-02-26 09:55
It looks like you accidentally sent your response to me instead of the OP.  Any idea how that happened?

**Comment by gileli121** [comment] 2022-02-26 11:06
@Pachat 
This is a bug that should be fixed by Microsoft.
And anyway I can't fix it myself.. I think that to fix it, you need source code of `C:\Windows\System32\dwm.exe` or something like that. Only Microsoft own it and can fix such issue because Windows is not open source product

**Comment by Pachat** [comment] 2022-02-26 11:26
@gileli121 
OK. Thank you for your answer. I don't know when Microsoft will have a true dark mode.
This kind of white flashing screen happens at anytime also opening Windows Explorer.
And on window search as soon a you type a letter, you get a white screen.
Anyway, these are Window problems.

**Comment by gileli121** [comment] 2022-02-27 07:46
@Pachat 
You should report about it.
It is possible that they missed the bug because it is almost unnoticeable.

I will close this issue.

**Closed by gileli121** 2022-02-27 07:46 UTC
Labels: need-more-info
