### ISSUE TITLE
[Anchors] Request: Choose color of anchor text and bullet point

### ISSUE THREAD

**Issue by camAtGitHub** [BiGilSoft/WindowTop#121] opened 2021-07-20 07:01 UTC
Hello.
Love your software and bought a license 💖 and now like the entitled software user I am, I now demand features I want! (sarcasm).  
But seriously: 

**The option to pick the color of the 'anchor' text and/or bullet point would be helpful.** 

Keep up the great work.

**Comment by gileli121** [comment] 2021-07-20 15:40
@camAtGitHub 
Thanks for your feedback!
Glad to hear that you like the software and the new feature!

About your request, do you mean to set color globally or per anchor?

**Comment by camAtGitHub** [comment] 2021-07-22 03:44
Personally I meant globally.

Many Thanks

**Comment by gileli121** [comment] 2021-09-02 22:14
@camAtGitHub 
Please try this build.

I added the following options:
![image](https://user-images.githubusercontent.com/17680514/131922382-24c3714b-e2ac-4823-8efc-b9be6701386c.png)

In "Visibility Configurations" you have these settings:
![image](https://user-images.githubusercontent.com/17680514/131922450-5c76f6ca-a3f1-425a-a122-ac548b541db3.png)

There are 2 things that I will explain:

* Highlight Color
* Regular Color

## Highlight Color
Let's say that you have 3 windows behind the main window.
The last window of these 3 windows is the most recent window that you used.
We can also think about "most recent window" as the first window that you see in the ALT+TAB windows list.

So the anchor of the most recent window will be in different color.
This is the idea.

Example:
![image](https://user-images.githubusercontent.com/17680514/131922767-17b2589b-7a85-48a4-b7b4-9755028e9c3d.png)

Now, if I choos to highlight 2 anchors
![image](https://user-images.githubusercontent.com/17680514/131922912-e2b7982a-c10c-42f7-a501-635901b5a86a.png)

It will use this color for the 2 most recent windows:
![image](https://user-images.githubusercontent.com/17680514/131922945-b79a615e-7daf-4855-bfc7-0b84e42e43df.png)


You can change the color by clicking on the color box
![image](https://user-images.githubusercontent.com/17680514/131922978-e11c5f3c-0fa5-47b7-b9b2-18c07cede31b.png)

If you don't want to highlight any window anchor, just disable it here:
![image](https://user-images.githubusercontent.com/17680514/131923049-b267340d-4ea3-4e02-9ce6-79a207e472e3.png)

## Regular Color

This is the regular color of the anchors
Here is what you asked for.. To change the color


Let me know what you think.

Here is the build:

[WindowTop Build 03-09-21_1.zip](https://github.com/BiGilSoft/WindowTop/files/7102053/WindowTop.Build.03-09-21_1.zip)

**Comment by camAtGitHub** [comment] 2021-09-03 13:07
Well done! I like the idea of two color pickers it certainly gives the user plenty of options to customize.  

My 2cents (feedback) is, personally I don't really like the 'drop shadows' around the text. It makes things harder to read/blurry especially at smaller sizes.  

Example:  

![image](https://user-images.githubusercontent.com/2858315/132008558-d218f10d-e7d6-4c5b-b6e4-c491b4a61f8a.png)  

Also the size configuration menu is a lot darker than other menus, Is it a renderer bug? or by design? 

![image](https://user-images.githubusercontent.com/2858315/132009928-a05982fa-4608-4769-baa3-63bfbbcab765.png)


If by design then it leads to my third piece of (unrequested) feedback. Please disable opacity for the settings! I can not stand it makes everything impossible to read!
I understand it's a bit of a show case to the program, but at least me set it 'back to normal' by using WindowTop on itself.

Thanks and nice work with the anchors!

**Comment by gileli121** [comment] 2021-09-03 14:21
@camAtGitHub 
How this looks:
![image](https://user-images.githubusercontent.com/17680514/132020727-352ee1c3-4afb-4283-bdb0-eceba6d45f36.png)

I also disabled the opacity here
![image](https://user-images.githubusercontent.com/17680514/132020784-94e76727-54dd-469a-a048-747f61e4f3d1.png)

**Comment by gileli121** [comment] 2021-09-03 15:50
@camAtGitHub
I don't think that there is solution for dark colors..
Even if I remove the drop shadow, it will be hard to read when the text is above dark background.
I think that you should not use dark colors any any case.

Here are good colors (I think) that you can choose
![image](https://user-images.githubusercontent.com/17680514/132033089-a33586d5-a96e-448f-b3a3-5bd44145aee1.png)


If it is still hard to read, you can make the font bigger here:
![image](https://user-images.githubusercontent.com/17680514/132033197-af0666cf-be67-4e4b-88c9-af1d72582af6.png)

**Comment by camAtGitHub** [comment] 2021-09-04 14:05
Using the 4-9-21 build (from https://github.com/BiGilSoft/WindowTop/issues/135) the 'Size Configuration' is all black.  
![image](https://user-images.githubusercontent.com/2858315/132097178-9ffa0fb8-a143-4b00-a7a4-5b2fc1232939.png)

  


Also, given the option I prefer the tight/non-blurry drop shadows you have here: ![here](https://user-images.githubusercontent.com/17680514/132020727-352ee1c3-4afb-4283-bdb0-eceba6d45f36.png)  
Thanks

**Comment by gileli121** [comment] 2021-09-04 20:59
@camAtGitHub 

1. OK, I reverted the fix that I did for the issue you showed at https://github.com/BiGilSoft/WindowTop/issues/121#issuecomment-912525643 
2. Which option is better?
This is how it looks by default:
![image](https://user-images.githubusercontent.com/17680514/132107713-682b901c-a445-4e7d-9c94-f7ab5bd9f432.png)

Option 1:
![image](https://user-images.githubusercontent.com/17680514/132107726-39d1c86b-cf3e-466a-9ab7-c5b42b800535.png)

Option 2:
![image](https://user-images.githubusercontent.com/17680514/132107902-6aa58b7e-83dc-4182-a0cd-1c98779d4a96.png)

3. This was intended because I don't want you to play with the opacity via the color picker.. But you know what, I changed it and now it will not ignore it.

**Comment by camAtGitHub** [comment] 2021-09-04 22:19
Hi @gileli121 have you got a build for me to play with?
Please and Thank you!

**Comment by gileli121** [comment] 2021-09-05 03:44
@camAtGitHub 
The reason I did not give build yet is that I am not sure about the drop shadow issue.
What I showed in this screenshot:
![image](https://user-images.githubusercontent.com/17680514/132114213-ca1b5307-3925-4d7b-bdb7-d4ac74983b13.png)

Was taken from 4k resolution and it did not look fine in 2k.

And I think that the drop shadow makes it easier to read when it is above bright backgrounds.
So I don't want to make it worse...

Maybe I should give the option to customize it but then we may end up with too complex settings

**Comment by gileli121** [comment] 2021-09-05 03:55
@camAtGitHub 
There is small change that I did
![image](https://user-images.githubusercontent.com/17680514/132114558-cb65d32e-f434-412b-8066-77d4ada71d83.png)

I changed the StrokeThickness from 1.5 to 2.5
and I also removed some shadow

Try this build:
[WindowTop Build 05-09-21_1.zip](https://github.com/BiGilSoft/WindowTop/files/7110871/WindowTop.Build.05-09-21_1.zip)

**Comment by gileli121** [comment] 2021-09-05 04:10
@camAtGitHub 
Please try this build also
[WindowTop Build 05-09-21_2.zip](https://github.com/BiGilSoft/WindowTop/files/7110879/WindowTop.Build.05-09-21_2.zip)

Here I did another small change in addition to the last change:
![image](https://user-images.githubusercontent.com/17680514/132114933-a54d0002-4961-476d-bc3b-dd909df4a62f.png)

Now the color of the stroke have small opacity. It's alpha is not 100%

**Comment by gileli121** [comment] 2021-12-26 22:24
@camAtGitHub
Can you share your feedback about this new improvement that it shows now icons?:
![anchors_demo](https://user-images.githubusercontent.com/17680514/147421180-3f94be81-6f19-4a4d-8bb6-567ee016184f.gif)

In addition, I also changed a little the default settings of the font size and width. 
It should be better now.

**Comment by camAtGitHub** [comment] 2021-12-27 22:40
Is there a build available or just the preview gif above?
Either way - it is looking very good. I like it. I can't wait to use it!

**Comment by gileli121** [comment] 2021-12-28 05:20
@camAtGitHub 
It is available in the last update.
It is also released in the store :)

**Closed** 2022-02-21 20:57 UTC
Labels: enhancement, done, testing...
